### PR TITLE
Setup

### PR DESCRIPTION
**Pull request by aokellermann**
### Changes
* Adds formatting/linting
* Adds testing
* Adds CI
* Adds package structure
* Adds README
* Adds setup script

---
This change is [Reviewable](https://reviewable.io/reviews/aokellermann/markdown_lt/1)

### CODE REVIEW

**Comment by maxitg** [comment]
Should I be using Reviewable or GitHub for reviews?

**Comment by aokellermann** [comment]
@maxitg reviewable should work now

**Review by maxitg — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/aokellermann/markdown_lt/1)* status: all files reviewed, 4 unresolved discussions (waiting on @aokellermann)

___
*[README.md, line 3 at r1](https://reviewable.io/reviews/aokellermann/markdown_lt/1#-MQsA_FiDlg5J9rhAn8G:-MQsA_FiDlg5J9rhAn8H:bllp4r1) ([raw file](https://github.com/aokellermann/markdown_lt/blob/118861a001a8bcfc61e326d66294935abedc1883/README.md#L3)):*
> ```Markdown
> # markdown_lt
> 
> [aokellermann](https://app.circleci.com/pipelines/github/aokellermann/markdown_lt)
> ```

The image seems [broken](https://github.com/aokellermann/markdown_lt/blob/feature/Setup/README.md).
___
*[.circleci/config.yml, line 6 at r1](https://reviewable.io/reviews/aokellermann/markdown_lt/1#-MQsCIF_Ciwkh6CRc39z:-MQsCIF_Ciwkh6CRc3A-:bs3j114) ([raw file](https://github.com/aokellermann/markdown_lt/blob/118861a001a8bcfc61e326d66294935abedc1883/.circleci/config.yml#L6)):*
> ```YAML
>   build:
>     docker:
>       - image: alpine
> ```

Would it make more sense to use the [Python orb](https://circleci.com/developer/orbs/orb/circleci/python)?
___
*[.circleci/config.yml, line 16 at r1](https://reviewable.io/reviews/aokellermann/markdown_lt/1#-MQsCSeM8BkGujkJoNtW:-MQsCSeM8BkGujkJoNtX:bgsff56) ([raw file](https://github.com/aokellermann/markdown_lt/blob/118861a001a8bcfc61e326d66294935abedc1883/.circleci/config.yml#L16)):*
> ```YAML
> 
>       - run:
>           name: Set Up Virtualenv
> ```

Maybe a naive question, but what is the benefit of this on CI where we only need a single environment?
___
*[scripts/format.sh, line 6 at r1](https://reviewable.io/reviews/aokellermann/markdown_lt/1#-MQsDGMK0wWM8PKhEojW:-MQsDGMK0wWM8PKhEojX:bnquy4u) ([raw file](https://github.com/aokellermann/markdown_lt/blob/118861a001a8bcfc61e326d66294935abedc1883/scripts/format.sh#L6)):*
> ```Shell
> 
> if [ "$#" -eq 0 ]; then
> 	yapf -d -r markdown_lt setup.py
> ```

Are you using tabs here intentionally? Asking because .py files use spaces.
___
*[scripts/format.sh, line 6 at r1](https://reviewable.io/reviews/aokellermann/markdown_lt/1#-MQsDkRF0-geWjC-gJTi:-MQsDkRF0-geWjC-gJTj:b5eq9tr) ([raw file](https://github.com/aokellermann/markdown_lt/blob/118861a001a8bcfc61e326d66294935abedc1883/scripts/format.sh#L6)):*
> ```Shell
> 
> if [ "$#" -eq 0 ]; then
> 	yapf -d -r markdown_lt setup.py
> ```

Just a suggestion, feel free to ignore, but I think using the full names of options makes the code more readable, e.g., `--diff --recursive`.
___
*[scripts/hooks/pre-push, line 3 at r1](https://reviewable.io/reviews/aokellermann/markdown_lt/1#-MQsFCk07SvU4y8eJx1l:-MQsFCk07SvU4y8eJx1m:b3njtkm) ([raw file](https://github.com/aokellermann/markdown_lt/blob/118861a001a8bcfc61e326d66294935abedc1883/scripts/hooks/pre-push#L3)):*
> ```
> #!/usr/bin/env bash
> 
> trap "echo 'Formatting and linting errors must be fixed before pushing!'" ERR
> ```

Whoa, that's magnificent! I should start using `trap` as well.

**Review by aokellermann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aokellermann/markdown_lt/1)* status: all files reviewed, 3 unresolved discussions (waiting on @maxitg)

___
*[README.md, line 3 at r1](https://reviewable.io/reviews/aokellermann/markdown_lt/1#-MQsA_FiDlg5J9rhAn8G:-MQxIfCoE9Lm5BW7nrgG:b-us302s) ([raw file](https://github.com/aokellermann/markdown_lt/blob/118861a001a8bcfc61e326d66294935abedc1883/README.md#L3)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

The image seems [broken](https://github.com/aokellermann/markdown_lt/blob/feature/Setup/README.md).
</blockquote></details>

Should be good now that repo is public.
___
*[.circleci/config.yml, line 6 at r1](https://reviewable.io/reviews/aokellermann/markdown_lt/1#-MQsCIF_Ciwkh6CRc39z:-MQxRFCkArRcP5x33Joj:bkq7qem) ([raw file](https://github.com/aokellermann/markdown_lt/blob/118861a001a8bcfc61e326d66294935abedc1883/.circleci/config.yml#L6)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Would it make more sense to use the [Python orb](https://circleci.com/developer/orbs/orb/circleci/python)?
</blockquote></details>

We would have to use either `pipenv` or `poetry` as a build system. I don't much reason to change to one of those. I've had bad experiences using anything other than `virtualenv`, especially with `pipenv` (look up "pipenv lock takes forever"). Also, we would have to use a second job for formatting/linting, since bash formatter/linter aren't available as python packages.

This gave me the idea to cache dependencies, though, so I added that.
___
*[.circleci/config.yml, line 16 at r1](https://reviewable.io/reviews/aokellermann/markdown_lt/1#-MQsCSeM8BkGujkJoNtW:-MQxJ2tf9g5wvVghs0xU:bp9uo9n) ([raw file](https://github.com/aokellermann/markdown_lt/blob/118861a001a8bcfc61e326d66294935abedc1883/.circleci/config.yml#L16)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Maybe a naive question, but what is the benefit of this on CI where we only need a single environment?
</blockquote></details>

It helps with running local python modules, as opposed to them being installed globally. 
___
*[scripts/format.sh, line 6 at r1](https://reviewable.io/reviews/aokellermann/markdown_lt/1#-MQsDGMK0wWM8PKhEojW:-MQxLc2n4RxUC7ROU1Um:b-1h9ahj) ([raw file](https://github.com/aokellermann/markdown_lt/blob/118861a001a8bcfc61e326d66294935abedc1883/scripts/format.sh#L6)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Are you using tabs here intentionally? Asking because .py files use spaces.
</blockquote></details>

Nice catch. Fixed.
___
*[scripts/format.sh, line 6 at r1](https://reviewable.io/reviews/aokellermann/markdown_lt/1#-MQsDkRF0-geWjC-gJTi:-MQxMJXvCGqmQQQq9jQ0:b-vjf152) ([raw file](https://github.com/aokellermann/markdown_lt/blob/118861a001a8bcfc61e326d66294935abedc1883/scripts/format.sh#L6)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Just a suggestion, feel free to ignore, but I think using the full names of options makes the code more readable, e.g., `--diff --recursive`.
</blockquote></details>

Good idea. Unfortunately `shfmt` doesn't provide full option names.

**Review by maxitg — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/aokellermann/markdown_lt/1)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
